---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"

  - package-ecosystem: pip
    directory: "/backend"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 15

    groups:
      pytest:
        patterns:
          - "pytest"
          - "pytest-*"

  - package-ecosystem: docker
    directory: "/backend"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: "/frontend"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
      time: "12:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope

    groups:
      lint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@adfinis/eslint-config"

          - "ember-template-lint"
          - "ember-template-lint-*"

          - "stylelint"
          - "stylelint-*"

          - "prettier"
          - "prettier-*"

      ember-core:
        patterns:
          - "ember-cli"
          - "ember-data"
          - "ember-source"

      ember:
        patterns:
          - "ember-*"
          - "@ember/*"

        exclude-patterns:
          - "ember-cli"
          - "ember-data"
          - "ember-source"

          - "ember-template-lint"
          - "ember-template-lint-*"
          - "ember-auto-import"
      js:
        patterns:
          - "*"
        exclude-patterns:
          - "ember-*"
          - "@ember/*"
          - "eslint"
          - "eslint-*"
          - "@adfinis/eslint-config"
          - "stylelint"
          - "stylelint-*"
          - "ember-auto-import"
          - "webpack"
          - "prettier"
          - "prettier-*"
