version: "3"

services:
  db:
    image: postgres:9.4
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=timed
      - POSTGRES_PASSWORD=timed

  frontend:
    build:
      context: .
    ports:
      - 4200:80

  backend:
    image: ghcr.io/adfinis/timed-backend:latest
    ports:
      - 8000:80
    depends_on:
      - db
      - mailpit
    environment:
      - DJANGO_DATABASE_HOST=db
      - DJANGO_DATABASE_PORT=5432
      - ENV=docker
      - DJANGO_EMAIL_USE_TLS=False
      - STATIC_ROOT=/var/www/static
      - EMAIL_URL=smtp://mailpit:1025
    command: /bin/sh -c "wait-for-it.sh -t 60 db:5432 -- ./manage.py migrate && ./manage.py loaddata timed/fixtures/test_data.json && uwsgi"

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_WEBROOT: mailpit
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


volumes:
  dbdata:
