apiVersion: v2
name: timed
description: Chart for Timed application
type: application
version: "0.0.0"
appVersion: "latest"
keywords:
  - timed
  - tracking
home: https://github.com/adfinis/timed
sources:
  - https://github.com/adfinis/timed
maintainers:
  - name: adfinis
    email: support@adfinis.com
    url: https://adfinis.com
dependencies:
  - name: postgresql
    version: "*"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "update timed-frontend to v3.6.0"
      links:
        - name: GitHub Release
          url: https://github.com/adfinis/timed-frontend/releases/tag/v3.6.0
