# Generated by Django 4.2.16 on 2024-09-17 08:50

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_report_search_vector_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='search_vector_idx',
        ),
        migrations.AddField(
            model_name='report',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tracking_re_search__35ab7c_gin'),
        ),
    ]
