# Generated by Django 5.2.15 on 2026-06-12 07:23

from __future__ import annotations
from django.contrib.postgres.fields import DateTimeRangeField
from typing import TYPE_CHECKING

from django.db.backends.postgresql.psycopg_any import DateTimeRange
from django.db import migrations, models

from datetime import datetime
from django.utils import timezone

if TYPE_CHECKING:
    from datetime import date as Date, time as Time


def date_time_to_datetime(date: Date, time: Time) -> datetime:
    return timezone.make_aware(datetime.combine(date, time))


def forward_migrate_times(apps, schema_editor):
    Activity = apps.get_model("tracking", "Activity")

    for activity in Activity.objects.iterator():
        date = activity.date

        start = date_time_to_datetime(date, activity.from_time)

        # running activities have to to_time
        end = None
        if to_time := activity.to_time:
            end = date_time_to_datetime(date, to_time)

        activity.range = DateTimeRange(start, end)
        activity.save(update_fields=["range"])


def reverse_migrate_times(apps, schema_editor):
    Activity = apps.get_model("tracking", "Activity")

    for activity in Activity.objects.filter(range__isnull=False).iterator():

        start = activity.range.lower
        activity.date = start.date()
        activity.from_time = start.time()

        # running activities have no upper bound
        if to := activity.range.upper:
            activity.to_time = to.time()

        activity.save(update_fields=["date", "from_time", "to_time"])


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0020_report_search_vector_trigger"),
    ]

    operations = [
        # add the range field, nullable for now
        migrations.AddField(
            model_name="activity",
            name="range",
            field=DateTimeRangeField(null=True),
        ),
        # make from-time and date nullable so reverting does not fail because of null values
        migrations.AlterField(
            model_name="activity",
            name="from_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateField(null=True),
        ),
        # migrate from date, from_time, to_time to range
        migrations.RunPython(forward_migrate_times, reverse_migrate_times),
        # make the range not-nullalbe
        migrations.AlterField(
            model_name="activity",
            name="range",
            field=DateTimeRangeField(),
        ),
        migrations.RemoveField(
            model_name="activity",
            name="date",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="from_time",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="to_time",
        ),
    ]
