# Generated by Django 5.2.12 on 2026-03-30 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_amount_invoiced_currency_and_more'),
        ('tracking', '0020_report_search_vector_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.task')),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prev_reports', to='projects.task')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.report')),
            ],
        ),
    ]
