# Generated by Django 5.2.10 on 2026-02-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0016_alter_location_workdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencetype',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
